---
name: '[Scheduled] Catalog (Update TrueNAS charts)'
on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_traefik:
    uses: ./.github/workflows/catalog.update.truecharts.yml
    with:
      train: stable
      app: traefik
