---
name: Catalog (Update TrueNAS charts)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: choice
        options:
          - traefik
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    environment: ${{ inputs.train }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: tibdex/github-app-token@da40f50387c080df631aba01ea5c6df3857145b7
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          ref: main
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          repository: truecharts/catalog
          ref: main
          path: vendors/truecharts
      - name: Sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
        run: |
          mkdir --parent ${{ inputs.train }}/${{ inputs.app }}
          rsync --archive --recursive --delete --verbose vendors/truecharts/${{ inputs.train }}/${{ inputs.app }}/ ${{ inputs.train }}/${{ inputs.app }}
          rm --recursive --force vendors/ "$(find ${{ inputs.train }}/${{ inputs.app }}/ -maxdepth 1 -mindepth 1 -type d | sort -rV | tail -n+6)"
      - uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: create-pr
        with:
          commit-message: sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
          author: Belug Apps <116495032+belug-apps[bot]@users.noreply.github.com>
          committer: Belug Apps <116495032+belug-apps[bot]@users.noreply.github.com>
          base: main
          body: ''
          branch: catalog/sync-${{ inputs.train }}-${{ inputs.app }}
          delete-branch: true
          signoff: true
          title: Sync catalog with TrueCharts one (${{ inputs.train }}/${{ inputs.app }})
      - uses: peter-evans/enable-pull-request-automerge@b3d5f7fa98684271559de54e61405dca9bb5c328
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          merge-method: squash
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          token: ${{ steps.app_auth.outputs.token }}
      - uses: hmarr/auto-approve-action@da92209ac68d76fd20af3efa5268a5e8fafb91d9
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          github-token: ${{ steps.app_auth.outputs.token }}
