---
name: Catalog (Update belug-apps chart)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      branch:
        description: belug-apps/belug-apps branch to synchronize with
        required: true
        default: main
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      branch:
        description: belug-apps/belug-apps branch to synchronize with
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          ref: main
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          repository: belug-apps/belug-apps
          ref: ${{ inputs.branch }}
          path: vendor/belug-apps
      - name: Find latest belug-apps version
        id: helm
        run: echo >> "$GITHUB_OUTPUT" "version=$(grep '^version:' vendor/belug-apps/charts/belug-apps/Chart.yaml | awk '{print $2}')"
      - name: Sync latest belug-apps version (${{ steps.helm.outputs.version }})
        run: rsync --archive --recursive --delete --verbose vendor/belug-apps/charts/belug-apps/ ${{ inputs.train }}/belug-apps/${{ steps.helm.outputs.version }}
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          add: ${{ inputs.train }}
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Sync belug-apps ${{ steps.helm.outputs.version }}
