---
name: '[Scheduled] Catalog (Sync TrueCharts charts)'
on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

permissions:
  pull-requests: write
  contents: write

jobs:
  sync_traefik:
    uses: ./.github/workflows/catalog.update.truecharts.yml
    secrets: inherit
    with:
      train: stable
      app: traefik
