---
name: Catalog (Update TrueNAS charts)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: choice
        options:
          - traefik
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    environment: ${{ inputs.train }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=1.7.0
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: main
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          repository: truecharts/catalog
          ref: main
          path: vendors/truecharts
      - name: Sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
        run: |
          mkdir --parent ${{ inputs.train }}/${{ inputs.app }}
          rsync --archive --recursive --delete --verbose vendors/truecharts/${{ inputs.train }}/${{ inputs.app }}/ ${{ inputs.train }}/${{ inputs.app }}
          # shellcheck disable=SC2046
          rm --recursive --force vendors/ $(find ${{ inputs.train }}/${{ inputs.app }}/ -maxdepth 1 -mindepth 1 -type d | sort -rV | tail -n+6 | xargs)
      - uses: peter-evans/create-pull-request@331d02c7e2104af23ad5974d4d5cbc58a3e6dc77 # v4.2.2
        id: create-pr
        with:
          commit-message: sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
          author: Belug Apps <116495032+belug-apps[bot]@users.noreply.github.com>
          committer: Belug Apps <116495032+belug-apps[bot]@users.noreply.github.com>
          base: main
          body: ''
          branch: catalog/sync-${{ inputs.train }}-${{ inputs.app }}
          delete-branch: true
          signoff: true
          title: Sync catalog with TrueCharts one (${{ inputs.train }}/${{ inputs.app }})
      - uses: peter-evans/enable-pull-request-automerge@127dd0d855f673047637945655ee76f0e9f239fe # tag=v2.2.1
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          merge-method: squash
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          token: ${{ steps.app_auth.outputs.token }}
      - uses: hmarr/auto-approve-action@de8ae18c173c131e182d4adf2c874d8d2308a85b # tag=v3.1.0
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          github-token: ${{ steps.app_auth.outputs.token }}
