---
name: Catalog (Update TrueNAS charts)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: choice
        options:
          - traefik
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    environment: ${{ inputs.train }}
    permissions:
      pull-requests: write
    steps:
      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          ref: main
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          repository: truecharts/catalog
          ref: main
          path: vendors/truecharts
      - name: Sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
        run: |
          mkdir --parent ${{ inputs.train }}/${{ inputs.app }}
          rsync --archive --recursive --delete --verbose vendors/truecharts/${{ inputs.train }}/${{ inputs.app }}/ ${{ inputs.train }}/${{ inputs.app }}
          rm -rf vendors
      - uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7
        id: create-pr
        with:
          commit-message: sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
          committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          base: main
          body: ''
          branch: catalog/sync-${{ inputs.train }}-${{ inputs.app }}
          delete-branch: true
          token: ${{ steps.app_auth.outputs.token }}
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          merge-method: squash
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          token: ${{ steps.app_auth.outputs.token }}
