---
name: '[External] Catalog (Update Belug-Apps chart)'
on: # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [sync-belugapps]

permissions:
  pull-requests: write
  contents: write

jobs:
  on_repository_dispatch:
    uses: ./.github/workflows/catalog.update.belug-apps.yml
    if: github.event.client_payload.ref != '' && github.event.client_payload.train != ''
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref }}
      train: ${{ github.event.client_payload.train }}
