---
name: Catalog (Update TrueNAS charts)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: choice
        options:
          - traefik
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      app:
        description: TrueCharts application to synchronize with
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    environment: ${{ inputs.train }}
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          ref: main
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          repository:  truecharts/charts
          ref: master
          path: vendor/truecharts
      - name: Sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
        run: rsync --archive --recursive --delete --verbose vendor/truecharts/charts/${{ inputs.train }}/${{ inputs.app }}/ ${{ inputs.train }}/${{ inputs.app }}
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          add: ${{ inputs.train }}
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Sync TrueChart ${{ inputs.train }}/${{ inputs.app }}
